apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: {{ include "deployment.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
     - name: {{ .name }}
       port: {{ .port }}
       targetport: {{ .port }}
       protocol: {{ .protocol }}
    {{- end }}
  selector:
    app: {{ include "deployment.fullname" . }}